import Head from 'next/head'

import { useRouter } from 'next/router'
import { useCookies } from 'react-cookie';
import { useEffect } from 'react';

export default function MyApp({ title }){

    const router = useRouter();
    const [cookies] = useCookies(['user']);

    useEffect(() => {
        if (cookies.user && cookies.user.User_ID) return;
        router.push('/');

    }, []);

    return (
        <Head>
            <title>{(title) ? title : 'GMMS'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}