import Head from 'next/head'

export default ({ title }) => {
    return (
        <Head>
            <title>{(title) ? title : 'GMMS'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}